spring:
  application:
    name: strava-wrapper
  jackson:
    default-property-inclusion: NON_NULL

server:
  servlet:
    context-path: /api/v3

logging:
  config: classpath:config/logback.xml

strava:
  archive:
    enabled: false
    directory: c:\\tmp\\archive-sim
  cache:
    path: c:\\tmp\\cache\\strava-cache-2025.ser
  auth:
    auth-file: src\\main\\resources\\config\\strava-token-local.properties
    host-url: http://localhost:12319
    oauthtoken-uri: /oauth/token
    client-id: 0000
    client-secret: 0000
    grant-type: refresh_token
    expiry-buffer: 180
  gear:
    b11683313: 
      name: SA
      description: Spa Audax
    b4500048: 
      name: H
      description: Claude Butler Hybrid
    b4500063: 
      name: F
      description: Fixed Wheel
    b4500064: 
      name: T
      description: Ridgeback Voyager Tourer
    b4500067: 
      name: R
      description: Ribble 364
    b4523173: 
      name: S
      description: Singlespeed
    b8592474: 
      name: Turbo
      description: Wattbike
    g11857474: 
      name: North Face Vectiv Enduris Futurelight Black winter waterproof trail shoes
      description: Size 12
    g12605013: 
      name: HOKA Speedgoat 5 Hoka trail shoes
      description: Wide fit
    g18691255: 
      name: Brooks Ghost 14 Grey Ghost
    g1957718: 
      name: ASICS Trounce 7
    g1973186: 
      name: Adidas Indoor Football
    g20117216: 
      name: ASICS GEL-PULSE 15 GTX Waterproof road shoes (2024)
    g3774380: 
      name: Brooks Revel
    g4019355: 
      name: ASICS Trainer DS 18 General Road Shoes
    g4609397: 
      name: Saucony Freedom iso 2 White Summer Road Shoes
    g6528683: 
      name: Saucony Peregrine Summer Trail shoes
    g6989782: 
      name: Saucony Peregrine 8 (GTX) Winter Trail Shoes
    g7267664: 
      name: ASICS GEL-PULSE 11 Winter Road Shoes
    g8081432: 
      name: ASICS Gel Cumulus 22 Blue Summer Running Shoes
    g8560275: 
      name: Brooks Ghost 12
      description: Wide fit
    g8878586: 
      name: HOKA Clifton 7
