spring:
  application:
    name: strava-wrapper

server:
  servlet:
    context-path: /api/v3

logging:
  config: classpath:config/logback.xml

strava:
#  config: file:///d:/workspace-sts/config/config.yml
  cache:
    path: c:\\tmp\\cache\\strava-cache-2025.ser