spring:
  application:
    name: strava-wrapper
  jackson:
    default-property-inclusion: NON_NULL

server:
  servlet:
    context-path: /api/v3

logging:
  config: classpath:config/logback.xml

strava:
  archive:
    enabled: true
    directory: c:\\tmp\\archive-sun
  cache:
    path: c:\\tmp\\cache\\strava-cache-2025.ser
  auth:
    auth-file: c:\\dev\\workspace\\GITHUB\\config\\dell\\strava-token.properties
    host-url: https://www.strava.com/api/v3
    oauthtoken-uri: /oauth/token
    client-id: 4270
    client-secret: cf147e77c98de2f5ee672d7736f63ff26d37d570
    grant-type: refresh_token
    expiry-buffer: 180
