spring:
  application:
    name: strava-wrapper
  jackson:
    default-property-inclusion: NON_NULL

server:
  servlet:
    context-path: /api/v3

logging:
  config: classpath:config/logback.xml

strava:
  archive:
    enabled: false
    directory: c:\\tmp\\archive
  cache:
    path: c:\\tmp\\cache\\strava-cache-2025.ser
  auth:
    auth-file: src\\main\\resources\\config\\strava-token-local.properties
    host-url: http://localhost:12319
    oauthtoken-uri: /oauth/token
    client-id: 0000
    client-secret: 0000
    grant-type: refresh_token
    expiry-buffer: 180
