spring:
  application:
    name: strava-wrapper
  jackson:
    default-property-inclusion: NON_NULL

server:
  servlet:
    context-path: /api/v3

logging:
  config: classpath:config/logback.xml

strava:
  config: classpath:config/config.yml
  cache:
    path: c:\\tmp\\cache\\strava-cache-2025.ser